### ISSUE TITLE
username unknown while auth-user-pass is set

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn/python-eduvpn-client#102]
while fixing #100 I encounter this error:

* add custom remote `debian-vpn.tuxed.net` 
* log in using LDAP credentials
* client gives assertion error, can't store config. Error is raised here:
https://github.com/eduvpn/python-eduvpn-client/blob/master/eduvpn/openvpn.py#L104
when `auth-user-pass` is set in the config, a username is expected in the metadata (and if not set it should not be set). In this case, `auth-user-pass` is set but the username not.
I think there is something wrong with the flow dictated from server side? `two_factor_enrolled` is not enabled in the `user_info` response.

@fkooman what do you think?

**Comment by fkooman** [comment]
If the user is not enrolled for 2FA it makes no sense to be able to configure the profile in the client. The user needs to be enrolled FIRST. The app could take care of this, like e.g. the Windows app does.

If the user is enrolled you can use the "user_info" call to retrieve for which 2FA method(s) the user is enrolled and use that user name in that case. 

https://github.com/eduvpn/documentation/blob/master/API.md#user-info

**Comment by gijzelaerr** [comment]
so we should just ignore the `auth-user-pass` config statement? it used to be only there if 2fa was enabled.

**Comment by fkooman** [comment]
No you can't ignore it, because connecting won't work then. If you obtain a profile that has 2FA enabled, which you can also see through the `/profile_list` call, https://github.com/eduvpn/documentation/blob/master/API.md#profile-list, the user MUST be enrolled for 2FA. So the best you can do is (after actually implementing 2FA enrolment, see, https://github.com/eduvpn/documentation/blob/master/API.md#two-factor-enrollment, which you already have?) give an error that the user needs to enrol first for 2FA.

Adding a profile that requires 2FA without the user actually being enrolled for 2FA does not make sense...

**Comment by gijzelaerr** [comment]
yes 2FA is implemented. Are you sure I should show an error? 

Let me ask the question differently; what does it mean if the server gives an `auth-user-pass` config line back?  As far as I know, I have not logged into `debian-vpn.tuxed.net` before, I've not enroled in anything. Behavior from the server until now was that it only started to add  `auth-user-pass` to the config when 2FA was expected.

**Comment by fkooman** [comment]
>  Behavior from the server until now was that it only started to add auth-user-pass to the config when 2FA was expected.

But 2FA *is* expected because 2FA is enabled for the `internet` profile on `debian-vpn.tuxed.net`, so the `auth-user-pass` line is exactly what you expect to get...

The only way a client can connect to this profile is by using 2FA, either with TOTP or YubiKey. If the user is not enrolled for either, connecting will never work.

There are two ways to deal with this:
1. implement TOTP/YubiKey **enrollment** in your application after which the user can use 2FA with 2FA enabled profile(s);
2. show an error that the user needs to enroll for 2FA in the user portal first before being able to connect to that profile.

The Windows app implements 1. All (desktop) clients should implement this.

**Comment by gijzelaerr** [comment]
It looks like the enrollment procedure has been added later? I don't remember reading about that in the flows. For now I'll implement 2 and open a new issue for 1.

![screenshot from 2018-05-16 14-35-21](https://user-images.githubusercontent.com/326308/40117175-76898152-5916-11e8-9e0d-4334de3460ee.png)
