### ISSUE TITLE
Reauthorize should not show "choose your profile" again

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#119]
Whenever the app gets revoked through the user portal account tab and you "reauthorize" it shows you the popup again to choose your profile. This is not expected as the profile was already chosen. This dialog is only needed when _adding_ a profile, *not* when reauthorizing.

**Comment by gijzelaerr** [comment]
This is one of those issues that take quite some time to reimplement since it would require a changes in the main subscription flow. Then it also has a risk of introducing new bugs and require testing. 

I think we need to ask ourselves how important this is compared to the investment is costs. Is it worth the time and effort and risk of introducing bugs compared to this one extra click a user needs to do in a situation that usually doesn't occur that much? 

I would classify this issue as low priority and nice to have for now.

**Comment by fkooman** [comment]
I think the biggest lesson here is that I underestimated how difficult it is to implement an API (using OAuth 2.0) at the client and expect everything to work properly. It is pretty easy to implement the "happy flow", however all edge cases I test (not just with the Linux client mind you, but also Android, iOS) are NOT accounted for and lead to problems. Maybe it is due to bad OAuth client libraries, or in general that using the OAuth libraries does NOT take away from the developer the need to understand OAuth, I am not sure... It's been a nightmare :cry:

**Comment by gijzelaerr** [comment]
i think the problem more is the GUI website, and also I underestimated the complexity involved in building a  multhreaded interactive UI. 

What could have helped for the API was to have a language-independent confirmation test suite, which you could use to tick all boxes to make sure all requirements are met. 

anyway, that is not the point. To my opinion, this might be confusing to the user, but this probably doesn't happen often, if it goes wrong the damage is low and the question is if it is worth to rewrite the subscription flow to prevent this issue.

**Comment by fkooman** [comment]
> have a language-independent confirmation test suite

how would this work? what would you be testing exactly? the API? the client? the server?

**Comment by gijzelaerr** [comment]
lets discuss that not in this issue :)

**Comment by gijzelaerr** [comment]
solved, with the new flow this is much easier.
