### ISSUE TITLE
No need to create new keypair per profile

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#151]
https://github.com/eduvpn/documentation/blob/master/API.md#create-a-key-pair

> NOTE: a keypair is valid for ALL profiles of a particular instance, so if an instance has e.g. the profiles internet and office, only one keypair is required!

**Comment by gijzelaerr** [comment]
by now I think we can conclude it would have been wise to store things like the keypairs separately from the VPN configurations and then create associations between them but I didn't. Keypairs are stored per profile. I can hack around that, but it is probably better to rewrite this at some point. This is not trivial since it would need to happen in a backward compatible way where people with existing eduVPN installation get their key store reconfigured. This then also needs to be properly tested.

I'm running out of hours for this development sprint, and since as far as i now his doesn't affect the end user experience I propose we don't do this for now. We can do this when we decide to rewrite the configuration storage.

**Comment by gijzelaerr** [comment]
This is going to be addressed in the 2.0.0 branch
