### ISSUE TITLE
replace pynacl by python-cryptography

### ISSUE THREAD

**Issue by fkooman** [eduvpn/python-eduvpn-client#207]
It supports ed25519: https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ed25519/

**Comment by fkooman** [comment]
This is for the discovery signature verification. This will change in the new discovery to be signify/minisign compatible.

**Comment by fkooman** [comment]
This is for the discovery signature verification. This will change in the new discovery to be signify/minisign compatible.

**Comment by fkooman** [comment]
The signature validation this refers to is described here: https://github.com/eduvpn/documentation/blob/v2/INSTANCE_DISCOVERY.md

The reason for wanting to do this is to reduce the number of dependencies and use as much as possible the "stdlib" of Python 3. There's no longer the need to support Python 2.

As far as I could tell, python-cryptography is an official part of Python 3?

**Comment by gijzelaerr** [comment]
there is https://docs.python.org/3/library/crypto.html but i don't see ed25519 support.

**Comment by amarsman** [comment]
python-cryptography is not an official part of Python 3.

CentOS 7.7 has a limited set of python3 libraries. There is a python2-cryptography which could be useful.

**Comment by amarsman** [comment]
Is https://www.pyinstaller.org/ ever considered?

PyInstaller freezes (packages) Python applications into stand-alone executables, under Windows, GNU/Linux, Mac OS X, FreeBSD, Solaris and AIX.

PyInstaller’s main advantages over similar tools are that PyInstaller works with Python 2.7 and 3.5—3.7, it builds smaller executables thanks to transparent compression, it is fully multi-platform, and use the OS support to load the dynamic libraries, thus ensuring full compatibility.

The main goal of PyInstaller is to be compatible with 3rd-party packages out-of-the-box. This means that, with PyInstaller, all the required tricks to make external packages work are already integrated within PyInstaller itself so that there is no user intervention required. You’ll never be required to look for tricks in wikis and apply custom modification to your files or your setup scripts. As an example, libraries like PyQt, Django or matplotlib are fully supported, without having to handle plugins or external data files manually.

**Comment by fkooman** [comment]
as for this specific issue: replacing one external dependency with another brings us not closer to simplifying the software substantially, so there is on point for now.

**Comment by gijzelaerr** [comment]
I realise now that we are already depending on the cryptography lib, so that changes this issue.

https://github.com/eduvpn/python-eduvpn-client/blame/master/setup.py#L21

lets give it a try for 2.0

**Comment by gijzelaerr** [comment]
This python-cryptography (2.3) in centos 8 doesn't contain the ed25519 functionality, so, unfortunately, we can't use it. Let's stick with NaCl.
