### ISSUE TITLE
Could not find a version that satisfies the requirement eduvpn_common

### ISSUE THREAD

**Issue by fantostisch** [eduvpn/python-eduvpn-client#511]
# Version

Commit 9fa97e8db194da5dfaaa3e1b76e5fa6611e072b8

# OS/Distribution

Debian Unstable

# Logs 
Running the commands in the README to build the client does not seem to work:

```
$ python3 -m venv venv
$ venv/bin/pip install ".[gui]"
Processing /home/nick/eduVPN/python-eduvpn-client
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement eduvpn_common (from eduvpn-client[gui]) (from versions: none)
ERROR: No matching distribution found for eduvpn_common
$ venv/bin/python --version
Python 3.10.9
```

**Comment by jwijenbergh** [comment]
That is because the latest pre-release does not have a pip package for all dependencies just yet, the instructions from the readme are for the current master branch.
For debian, I recommend to not use pip anyways https://python-eduvpn-client.readthedocs.io/en/master/installation.html#debian-and-ubuntu

Or for the latest pre-release follow the pre-release docs https://github.com/eduvpn/python-eduvpn-client/releases/tag/pr-3.2.0 (this version contains lots of fixes).

If you still want to use pip with the latest stable release, run 

```venv/bin/pip install "eduvpn-client[gui]"```

**Comment by jwijenbergh** [comment]
Cool! If there are any issues feel free to open them in this repo
