### ISSUE TITLE
Disconnect vpn on app close

### ISSUE THREAD

**Issue by jwijenbergh** [eduvpn/python-eduvpn-client#518]
Should the VPN disconnect on app close? Related to #517 

This is so that the client calls /disconnect to the server on app close. Which saves IP resources on the server, but maybe not ideal behaviour?

**Comment by jwijenbergh** [comment]
I agree, the main problem is the lack of a unified tray API. But StatusNotifier is probably good enough to implement. This is something i have been meaning to pick up

See #352

**Comment by fkooman** [comment]
There are a few situation, the focus so far in the replies here is on only the first one:

1. The user closes the application using the [X];
2. The users logs out
3. The user shuts down the system

Perhaps (2) and (3) are actually the same from the app's point of view, but they should *definitely* disconnect the VPN.

As for (1), I think it depends on the OS. If you are using GNOME, closing the app should disconnect, if you run on KDE (and KDE actually has a tray?) it could minimize to tray.

In either case, the current behavior is weird, because you "lose" the UI and can't find it anymore, except by restarting the app.

So short term, until tray stuff is implemented, a "quit" of the application, either directly by user, or by logout or by shutdown should disconnect the VPN.

**Comment by jwijenbergh** [comment]
I am closing this issue, I don't see anything actionable here. Regarding system tray, I have put it on very low priority for now as the APIs for it suck to say the least
