### ISSUE TITLE
ERROR - no profiles found with supported protocols 

### ISSUE THREAD

**Issue by jessebelleman** [eduvpn/python-eduvpn-client#559]
# Installation

How did you install the eduVPN/Let's Connect! client?

I used the pip install "eduvpn-client[GUI]" since my ubuntu version 18.04 was not in the list.

# Version

What version of the client you are running? Try your package manager or otherwise `eduvpn-gui -v` or `letsconnect-gui -v`.

eduVPN GUI version: 4.1.3 with eduvpn-common version: 1.1.2

# OS/Distribution

ubuntu 18.04

# Logs
The following error occurs in the log when I click on 'university of amsterdam'  within the institute access section:

2023/11/07 13:15:15 - Go - ERROR - no profiles found with supported protocols

**Comment by jwijenbergh** [comment]
Would you be able to try with a more up to date ubuntu? I think it's because ubuntu 18.04 does not support the protocol (WireGuard) that might be used here. Do other clients work? I recommend to update to a newer ubuntu anyways because ubuntu 18.04 is ancient at this point and not officially supported anymore by us

**Comment by jwijenbergh** [comment]
Closing due to no response
