### ISSUE TITLE
Ubuntu 16.04.3 LTS > 'property 'tls-cipher' invalid or not supported'

### ISSUE THREAD

**Issue by mkoelewijn** [eduvpn/python-eduvpn-client#92]
Whenever i try to start the VPN i get a error 'property 'tls-cipher' invalid or not supported'. However when you download the config straight from nl.eduvpn.org the configuration works as well with the eduVPN app as with NetworkManager:

<img width="755" alt="screen shot 2017-10-23 at 21 56 04" src="https://user-images.githubusercontent.com/26085443/31911048-b3940a86-b83f-11e7-8d15-9c0618b1adfa.png">

After examining the configuration options through the NetworkManager settings i noticed the option  "Use LZO data compression" was not set for the configuration that the eduVPN app created. After i enabled this option i am able to connect with this configuration through NetworkManager but not with eduVPN > when i try to start it again with eduVPN the (LZO compression) option is unset again.

**Comment by gijzelaerr** [comment]
ok so the problem is network manager, specifically the openvpn plugin.

* Ubuntu 16.04 has NM 1.2.6, openvpn plugin 1.1.93
* Ubuntu 17.04 has  NM 1.4.4, openvpn plugin 1.2.6
* Ubuntu 17.10 has NM 1.8.4, openvpn plugin 1.2.10
* Debian 9 has NM  1.6.2, openvpn plugin 1.2.8

Documentation for NM can be found here https://developer.gnome.org/NetworkManager/, but the openvpn plugin seems undocumented...

This commit adds support for the flag.
https://git.gnome.org/browse/network-manager-openvpn/commit/?id=0bb5562a2c8b1924eeb3c671f28853aaaabf70f4

which has a `git describe` looking `1.2.3-dev-16-g0bb5562`, which suggests this is only supported in `1.2.3+`.

**Comment by gijzelaerr** [comment]
removing the `tls-cipher` option and setting  `comp-lzo` to `yes` seems to solve the problem, and also works on Debian 9.

**Comment by gijzelaerr** [comment]
https://github.com/eduvpn/python-eduvpn-client/commit/1ea47385ebf86ce43e1cd827a88f64face19908b
